---
title: "Ripple/XRP_Price_Prediction"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(purrr)
library(tidyverse)
```


```{r}
#Historical data from Yahoo Finance

#cryptocurrency historical prices (USD)
xrp <- read.csv("XRP-USD.csv")%>% rename(Open_xrp = Open, High_xrp = High, Low_xrp = Low, Close_xrp = Close, Adj.Close_xrp = Adj.Close, Volume_xrp = Volume)
btc <- read.csv("BTC-USD.csv")%>% rename(Open_btc = Open, High_btc = High, Low_btc = Low, Close_btc = Close, Adj.Close_btc = Adj.Close, Volume_btc = Volume)

#stock index historical data
dowJones <- read.csv("^DJI(djia).csv")%>% rename(Open_dow = Open, High_dow = High, Low_dow = Low, Close_dow = Close, Adj.Close_dow = Adj.Close, Volume_dow = Volume)
sAndP <- read.csv("^GSPC(S&P500).csv")%>% rename(Open_sandp = Open, High_sandp = High, Low_sandp = Low, Close_sandp = Close, Adj.Close_sandp = Adj.Close, Volume_sandp = Volume)
nasdaq <- read.csv("^IXIC(nasdaq).csv")%>% rename(Open_nasdaq = Open, High_nasdaq = High, Low_nasdaq = Low, Close_nasdaq = Close, Adj.Close_nasdaq = Adj.Close, Volume_nasdaq = Volume)
nyse <- read.csv("^NYA (nyse).csv")%>% rename(Open_nyse = Open, High_nyse = High, Low_nyse = Low, Close_nyse = Close, Adj.Close_nyse = Adj.Close, Volume_nyse = Volume)

#NY Mercantile Delayed Price (USD)
oilFutures <- read.csv("CL=F ( crude oil futures).csv")%>% rename(Open_oil = Open, High_oil = High, Low_oil = Low, Close_oil = Close, Adj.Close_oil = Adj.Close, Volume_oil = Volume)

#COMEX Delayed Price (USD)
goldFutures <- read.csv("GC=F.csv")%>% rename(Open_gold = Open, High_gold = High, Low_gold = Low, Close_gold = Close, Adj.Close_gold = Adj.Close, Volume_gold = Volume)
silverFutures <- read.csv("SI=F.csv")%>% rename(Open_silver = Open, High_silver = High, Low_silver = Low, Close_silver = Close, Adj.Close_silver = Adj.Close, Volume_silver = Volume)

xrp
btc
dowJones
sAndP
nasdaq
nyse
oilFutures
goldFutures
silverFutures

```


```{r }
#Modify date formatting to uniform
dfList <- list(btc,sAndP,nasdaq,nyse,oilFutures,goldFutures,silverFutures)
dfList <- lapply(dfList, function(x) {
                    x$Date <- strptime(as.character(x$Date), "%Y-%m-%d")
                    x$Date <- format(x$Date, "%m/%d/%Y")
                    print(x)} )
btc=dfList[[1]]
sAndP=dfList[[2]]
nasdaq=dfList[[3]]
nyse=dfList[[4]]
oilFutures=dfList[[5]]
goldFutures=dfList[[6]]
silverFutures=dfList[[7]]

#Dataframes with different format than above
dfList2 <- list(xrp,dowJones)
dfList2 <- lapply(dfList2, function(x) {
                    x$Date <- strptime(as.character(x$Date), "%m/%d/%Y")
                    x$Date <- format(x$Date, "%m/%d/%Y")
                    print(x)} )
xrp=dfList2[[1]]
dowJones=dfList2[[2]]


#Merge dataframes into one dataset
data <- list(xrp,btc,dowJones,nasdaq,nyse,sAndP,goldFutures,silverFutures,oilFutures) %>% reduce(full_join, by = "Date")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
