---
title: "xrpdataexploration"
author: "Alyssa Smith"
date: "4/8/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tseries)
library(Boruta)
library(zoo)
library(vars)
```



```{r}
#Augmented Dickey Fuller Stationarity test for High_XRP
adf.test(data$High_xrp)
```

```{r}
#Perform boruta test for feature selection (wrapper around random forest)
boruta_output <- Boruta(High_xrp ~ ., data=na.omit(data))
# collect Confirmed and Tentative variables
boruta_signif <- names(boruta_output$finalDecision[boruta_output$finalDecision %in% c("Confirmed", "Tentative")]) 
plot(boruta_output, cex.axis=.7, las=2, xlab="", main="Variable Importance")  # plot variable importance
```

```{r}
#Augmented Dickey Fuller Stationarity testing for various highly important predictor variables
adf.test(data$High_btc) #Lag order = 12,p-value = 0.2474
adf.test(data$Adj.Close_btc) #Lag order = 12, p-value = 0.2216
adf.test(data$Low_btc) #Lag order = 12, p-value = 0.3705
adf.test(data$High_oil)#Lag order = 12, p-value = 0.9264
adf.test(data$High_nasdaq) #Lag order = 12, p-value = 0.0293
adf.test(data$Close_oil)#Lag order = 12, p-value = 0.9374
adf.test(data$Close_silver)#Lag order = 12, p-value = 0.2795
adf.test(data$High_silver)#Lag order = 12, p-value = 0.2602
adf.test(data$Low_silver) #Lag order = 12, p-value = 0.3058
adf.test(data$Adj.Close_dow)#Lag order = 12, p-value = 0.3719
adf.test(data$Open_dow)#Lag order = 12, p-value = 0.3989
adf.test(data$Open_nasdaq)#Lag order = 12, p-value = 0.02382


#Experimenting with various lag orders 
adf.test(data$High_btc, k=2) #Lag order = 2, p-value = 0.4582
adf.test(data$High_btc, k=5) #Lag order = 5, p-value = 0.3979
adf.test(data$High_btc, k=20) #Lag order = 20, p-value = 0.183
adf.test(data$High_btc, k=40) #Lag order = 40, p-value = 0.3487
```
```{r}
#Differencing non-stationary variables from above

plot.ts(data$High_btc)
High_btc_diff <- diff(data$High_btc, differences=1)
plot.ts(High_btc_diff)
adf.test(High_btc_diff)


Adj.Close_btc_diff <- diff(data$Adj.Close_btc, differences=1)
plot.ts(Adj.Close_btc_diff)
adf.test(Adj.Close_btc_diff)


Low_btc_diff <- diff(data$Low_btc, differences=1)
plot.ts(Low_btc_diff)
adf.test(Low_btc_diff)


High_oil_diff <- diff(data$High_oil, differences=1)
plot.ts(High_oil_diff)
adf.test(High_oil_diff)


Close_oil_diff <- diff(data$Close_oil, differences=1)
plot.ts(Close_oil_diff)
adf.test(Close_oil_diff)


Close_silver_diff <- diff(data$Close_silver, differences=1)
plot.ts(Close_silver_diff)
adf.test(Close_silver_diff)


High_silver_diff <- diff(data$High_silver, differences=1)
plot.ts(High_silver_diff)
adf.test(High_silver_diff)

Low_silver_diff <- diff(data$Low_silver, differences=1)
plot.ts(Low_silver_diff)
adf.test(Low_silver_diff)

#-------------
Adj.Close_dow_diff <- diff(data$Adj.Close_dow, differences=1)
plot.ts(Adj.Close_dow_diff)
adf.test(Adj.Close_dow_diff)


Open_dow_diff <- diff(data$Open_dow, differences=1)
plot.ts(Open_dow_diff)
adf.test(Open_dow_diff)

#All tested variables successfully passed the ADF stationarity test after lag-1 differencing.
```


```{r}

#Create dataframes for Granger Causality Test to determine importance in predicting High_XRP (using the stationary features above)
#Needed to remove first column of High_xrp because of how the differencing works: the count of the differenced data was one less than the original column
highBTC = data.frame(data$High_xrp[-1], High_btc_diff)
grangertest(highBTC[[1]] ~ highBTC[[2]], order = 3, data = highBTC)  #p-value: 0.00082

adjCloseBTC = data.frame(data$High_xrp[-1], Adj.Close_btc_diff)
grangertest(adjCloseBTC[[1]] ~ adjCloseBTC[[2]], order = 3, data = adjCloseBTC)  #p-value: < 2.2e-16

lowBTC = data.frame(data$High_xrp[-1], Low_btc_diff)
grangertest(lowBTC[[1]] ~ lowBTC[[2]], order = 3, data = lowBTC)   #p-value: < 2.2e-16

highOil = data.frame(data$High_xrp[-1], High_oil_diff)
grangertest(highOil[[1]] ~ highOil[[2]], order = 3, data = highOil)  #p-value: 0.9494

highNASDAQ = data.frame(data$High_xrp, data$High_nasdaq)
grangertest(highNASDAQ[[1]] ~ highNASDAQ[[2]], order = 3, data = highNASDAQ)  #p-value: 0.6872

CloseOil = data.frame(data$High_xrp[-1], Close_oil_diff)
grangertest(CloseOil[[1]] ~ CloseOil[[2]], order = 3, data = CloseOil)#p-value: 0.7832

CloseSilver = data.frame(data$High_xrp[-1], Close_silver_diff)
grangertest(CloseSilver[[1]] ~ CloseSilver[[2]], order = 3, data = CloseSilver)#p-value: 0.3482

highSilver = data.frame(data$High_xrp[-1], High_silver_diff)
grangertest(highSilver[[1]] ~ highSilver[[2]], order = 3, data = highSilver)#p-value: 0.5557

lowSilver = data.frame(data$High_xrp[-1], Low_silver_diff)
grangertest(lowSilver[[1]] ~ lowSilver[[2]], order = 3, data = lowSilver)#p-value: 0.371

adjCloseDow = data.frame(data$High_xrp[-1], Adj.Close_dow_diff)
grangertest(adjCloseDow[[1]] ~ adjCloseDow[[2]], order = 3, data = adjCloseDow)#p-value: 0.4515

openDow = data.frame(data$High_xrp[-1], Open_dow_diff)
grangertest(openDow[[1]] ~ openDow[[2]], order = 3, data = openDow)#p-value: 0.2341

openNASDAQ = data.frame(data$High_xrp, data$Open_nasdaq)
grangertest(openNASDAQ[[1]] ~ openNASDAQ[[2]], order = 3, data = openNASDAQ)  #p-value: 0.5928

#Only the first 3 values showed a probable causality relationship: high BTC price, Adj.Close BTC, and low BTC.
```

